spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  mvc:
    hiddenmethod:
      filter:
        enabled: true

springdoc:
  api-docs:
    path: api-docs
server:
  port: 9090